name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Run parser tests
      run: ./gradlew parser:test
      env:
        GITHUB_API_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}


  lint:
    name: Run ktlint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1.1.0
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          reporter: github-pr-review
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
